#!/usr/bin/env python3
"""
export.py -- pulls saved titles out of a kolonka sie_titles.db and writes,
per volume, into data/:
  - <volume>.csv  everything, in scan (page) order -- for programmatic use
  - <volume>.md   a simplified table, alphabetically sorted -- renders
                   directly in the GitHub browser as a browsable index

Usage:
    python3 export.py /path/to/sie_titles.db
    python3 export.py /path/to/sie_titles.db --volume СИЭ-01   # just one volume
"""

import argparse
import csv
import sqlite3
from pathlib import Path


def title_sort_key(title):
    """Same rule as the kolonka editor's /titles page: case-insensitive,
    ignoring spaces/hyphens/commas, and ignoring a leading «."""
    t = (title or "").lower()
    for ch in (" ", "-", ","):
        t = t.replace(ch, "")
    if t.startswith("«"):
        t = t[1:]
    return t


def md_escape(s):
    return (s or "").replace("|", "\\|").replace("\n", " ")


def export_csv(rows, out_path):
    with open(out_path, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow([
            "page", "column", "column_page", "column_page_end",
            "guessed", "title", "bold_ratio", "first_line",
        ])
        w.writerows(rows)


def export_md(rows, out_path, volume):
    # rows: page, column, column_page, column_page_end, guessed, title, bold_ratio, first_line
    sorted_rows = sorted(rows, key=lambda r: (title_sort_key(r[5]), r[0]))

    lines = [
        f"# {volume}",
        "",
        f"{len(rows)} entries. Sorted alphabetically. `*` after a printed "
        "page number means it was extrapolated rather than read directly "
        "from that page's own header -- see the main "
        "[kolonka](https://github.com/fukanchik/kolonka) repo for how that "
        "works. Generated by `export.py`; do not hand-edit.",
        "",
        "| Title | Page | Printed # |",
        "|---|---|---|",
    ]
    for page, _column, column_page, column_page_end, guessed, title, _bold_ratio, _first_line in sorted_rows:
        if column_page is None:
            printed = ""
        elif column_page_end:
            printed = f"{column_page}\u2013{column_page_end}"
        else:
            printed = str(column_page)
        if printed and guessed:
            printed += "\\*"
        lines.append(f"| {md_escape(title)} | {page} | {printed} |")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def export_volume(conn, volume, out_dir):
    rows = conn.execute(
        """SELECT page, "column", column_page, column_page_end, guessed,
                  title, bold_ratio, first_line
           FROM titles WHERE volume=? ORDER BY page, id""",
        (volume,),
    ).fetchall()

    csv_path = out_dir / f"{volume}.csv"
    md_path = out_dir / f"{volume}.md"
    export_csv(rows, csv_path)
    export_md(rows, md_path, volume)

    print(f"{volume}: wrote {len(rows)} rows to {csv_path} and {md_path}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("db_path", help="Path to sie_titles.db")
    ap.add_argument("--volume", default=None, help="Export just this volume (default: all)")
    ap.add_argument("--out", default="data", help="Output directory (default: data/)")
    args = ap.parse_args()

    out_dir = Path(args.out)
    out_dir.mkdir(exist_ok=True)

    conn = sqlite3.connect(args.db_path)
    if args.volume:
        volumes = [args.volume]
    else:
        volumes = [r[0] for r in conn.execute("SELECT DISTINCT volume FROM titles ORDER BY volume")]

    if not volumes:
        print("No volumes found in this database.")
        return

    for v in volumes:
        export_volume(conn, v, out_dir)


if __name__ == "__main__":
    main()
