#!/usr/bin/env python3
"""
export.py -- pulls saved titles out of a kolonka sie_titles.db and writes,
per volume, into data/:
  - SIE-<NN>.csv  everything, in scan (page) order -- for programmatic use
  - SIE-<NN>.md   a simplified table, alphabetically sorted -- renders
                   directly in the GitHub browser as a browsable index

In the .md output, the Page column links to the matching page on
Internet Archive when the volume has a scan there. The Soviet
Historical Encyclopedia's 16 volumes are archived at Internet Archive
under identifiers "B-001-026-938-01" through "-16" (volume 11 is the
one exception with no scan there, as of writing) -- see
https://ru.wikisource.org/wiki/Советская_историческая_энциклопедия
for the source listing. The volume number is read straight out of the
volume name (e.g. "СИЭ-03" -> 3), so this works automatically for any
volume named the same way, without a separate lookup table.

Internet Archive's page-in-URL numbering doesn't line up 1:1 with this
encyclopedia's own scanned-page numbering -- e.g. for volume 1,
.../page/n11/mode/2up displays as "page 11-12" in the viewer, but that
same leaf is page 13 in the djvu. The exact relationship hasn't been
pinned down yet, so this uses a single constant offset (see
--archive-page-offset) as a first approximation: archive_n = page -
offset. The default (1) is almost certainly not exactly right for
every page -- adjust it once you've checked more examples, or pass 0
to just link straight to the page number with no adjustment.

Usage:
    python3 export.py /path/to/sie_titles.db
    python3 export.py /path/to/sie_titles.db --volume СИЭ-01   # just one volume
    python3 export.py /path/to/sie_titles.db --archive-page-offset 2
    python3 export.py /path/to/sie_titles.db --no-archive-links
"""

import argparse
import csv
import re
import sqlite3
from pathlib import Path

ARCHIVE_ID_TEMPLATE = "B-001-026-938-{:02d}"
NO_ARCHIVE_VOLUMES = {11}  # volumes known to have no Internet Archive scan


def title_sort_key(title):
    """Same rule as the kolonka editor's /titles page: case-insensitive,
    ignoring spaces/hyphens/commas, and ignoring a leading «."""
    t = (title or "").lower()
    for ch in (" ", "-", ","):
        t = t.replace(ch, "")
    if t.startswith("«"):
        t = t[1:]
    return t


def md_escape(s):
    return (s or "").replace("|", "\\|").replace("\n", " ")


def volume_number(volume):
    """Pulls the trailing volume number out of a volume name, e.g.
    'СИЭ-03' -> 3, 'vol01' -> 1. Returns None if no trailing digits."""
    m = re.search(r"(\d+)$", volume)
    return int(m.group(1)) if m else None


def archive_id_for_volume(volume):
    """Internet Archive identifier for this volume, or None if unknown/unavailable."""
    num = volume_number(volume)
    if num is None or num in NO_ARCHIVE_VOLUMES:
        return None
    return ARCHIVE_ID_TEMPLATE.format(num)


def export_csv(rows, out_path):
    with open(out_path, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow([
            "page", "column", "column_page", "column_page_end",
            "guessed", "title", "bold_ratio", "first_line",
        ])
        w.writerows(rows)


def page_cell(page, archive_id, offset):
    """Markdown for the Page column: a link to Internet Archive if we
    have an archive_id for this volume, else the plain page number."""
    if archive_id is None:
        return str(page)
    archive_n = page - offset
    if archive_n < 1:
        return str(page)  # offset would point before the start of the scan; don't guess
    url = f"https://archive.org/details/{archive_id}/page/n{archive_n}/mode/2up"
    return f"[{page}]({url})"


def export_md(rows, out_path, volume, archive_id, offset):
    # rows: page, column, column_page, column_page_end, guessed, title, bold_ratio, first_line
    sorted_rows = sorted(rows, key=lambda r: (title_sort_key(r[5]), r[0]))

    archive_note = (
        f"Page links go to the matching scan on "
        f"[Internet Archive](https://archive.org/details/{archive_id}) "
        f"(page numbers there are offset by {offset} from this encyclopedia's "
        f"own numbering -- not yet confirmed exact for every page)."
        if archive_id else
        "No Internet Archive scan is linked for this volume."
    )

    lines = [
        f"# {volume}",
        "",
        f"{len(rows)} entries. Sorted alphabetically. {archive_note} `*` after "
        "a printed page number means it was extrapolated rather than read "
        "directly from that page's own header -- see the main "
        "[kolonka](https://github.com/fukanchik/kolonka) repo for how that "
        "works. Generated by `export.py`; do not hand-edit.",
        "",
        "| Title | Page | Printed # |",
        "|---|---|---|",
    ]
    for page, _column, column_page, column_page_end, guessed, title, _bold_ratio, _first_line in sorted_rows:
        if column_page is None:
            printed = ""
        elif column_page_end:
            printed = f"{column_page}\u2013{column_page_end}"
        else:
            printed = str(column_page)
        if printed and guessed:
            printed += "\\*"
        lines.append(f"| {md_escape(title)} | {page_cell(page, archive_id, offset)} | {printed} |")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def output_stem(volume):
    """Filesystem-friendly output name: SIE-<NN> when the volume name ends
    in a number (the normal case), else fall back to the raw volume name
    rather than crash on something unexpected."""
    num = volume_number(volume)
    return f"SIE-{num:02d}" if num is not None else volume


def export_volume(conn, volume, out_dir, archive_links, offset):
    rows = conn.execute(
        """SELECT page, "column", column_page, column_page_end, guessed,
                  title, bold_ratio, first_line
           FROM titles WHERE volume=? ORDER BY page, id""",
        (volume,),
    ).fetchall()

    archive_id = archive_id_for_volume(volume) if archive_links else None

    stem = output_stem(volume)
    csv_path = out_dir / f"{stem}.csv"
    md_path = out_dir / f"{stem}.md"
    export_csv(rows, csv_path)
    export_md(rows, md_path, volume, archive_id, offset)

    note = f"archive={archive_id}" if archive_id else "no archive link"
    print(f"{volume}: wrote {len(rows)} rows to {csv_path} and {md_path} ({note})")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("db_path", help="Path to sie_titles.db")
    ap.add_argument("--volume", default=None, help="Export just this volume (default: all)")
    ap.add_argument("--out", default="data", help="Output directory (default: data/)")
    ap.add_argument("--archive-page-offset", type=int, default=1,
                     help="djvu page number minus this = Internet Archive's page/nNN number (default: 1)")
    ap.add_argument("--no-archive-links", action="store_true",
                     help="Don't link the Page column to Internet Archive")
    args = ap.parse_args()

    out_dir = Path(args.out)
    out_dir.mkdir(exist_ok=True)

    conn = sqlite3.connect(args.db_path)
    if args.volume:
        volumes = [args.volume]
    else:
        volumes = [r[0] for r in conn.execute("SELECT DISTINCT volume FROM titles ORDER BY volume")]

    if not volumes:
        print("No volumes found in this database.")
        return

    for v in volumes:
        export_volume(conn, v, out_dir, not args.no_archive_links, args.archive_page_offset)


if __name__ == "__main__":
    main()
